### ISSUE TITLE
How to download the train dataset?

### ISSUE THREAD

**Issue by tobegit3hub** [cameronfabbri/Colorful-Image-Colorization#1]
The project is great and we would like to train locally.

How can we download the train dataset? It seems we can set the data path but there's no image files.

![screen shot 2016-11-10 at 23 33 48](https://cloud.githubusercontent.com/assets/2715000/20182865/38b9553a-a79e-11e6-8a2b-0a054580e8d7.png)

**Comment by cameronfabbri** [comment]
Hi,

Thank you!

So I actually created the dataset myself. I'm not sure if I can just put up
the images anywhere because there's a ton of them, and I'm not sure of a
site that would host them. What I did was I went to Youtube and downloaded
a bunch of walkthroughs like this one.
https://www.youtube.com/watch?v=Ni2IC-KNbfc

and used ffmpeg to extract frames. The script I used to extract frames is
in the utils folder, just pass it the location of the video as an argument.
After the frames are extracted, for some videos (like the one above) you'll
need to crop out the border that was in the youtube video. For that you can
use the script crop_images.py also in the utils folder. You may have to
edit it because I used it for different videos, so just uncomment the
opencv stuff to view the image, and make sure that your cropping is correct
before running it on all images. After that is done, you will need to
prepare the images for tensorflow, i.e resizing them and creating gray
images. For that you can use the convert_images.py script also in the utils
folder. That will for each image create a copy that is of resolution
(160,144) (gameboy color resolution) and also create a gray image of
(160,144). Look at the comments at the top of the file to see what I mean
by that. After that is finished, that is the 'data_dir' that you pass to
the train script. I didn't realize people would use this, so I didn't make
a readme for instructions, but I guess I will now! Any other questions feel
free to ask.

Cameron

**Comment by tobegit3hub** [comment]
@cameronfabbri Thanks for response and the project is really great for me 👍 

I'm not sure if I can download the youtube video and extract all the frames. But it would be great if you provide a few training images so that I can walkthrough the training process. Your instructions are detailed and helpful. Please add them in README.md if you don't mind.

**Comment by cameronfabbri** [comment]
Yep doing that now. I'll also add some images in the images folder with
instructions on how to use them.

**Comment by cameronfabbri** [comment]
I updated the project, were you able to figure it out?
